// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

namespace Persistence.Migrations
{
    [DbContext(typeof(AcDataContext))]
    [Migration("20201208165608_EmployeeEmtityAdded")]
    partial class EmployeeEmtityAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Venue")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("Domain.Employee", b =>
                {
                    b.Property<string>("Number")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AdminAssistant")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("BillingTitle")
                        .HasColumnType("smallint");

                    b.Property<bool>("CVCbxEAMVehicle")
                        .HasColumnType("bit");

                    b.Property<bool>("CVCbxEDMVehicle")
                        .HasColumnType("bit");

                    b.Property<bool>("CVCbxGasCard")
                        .HasColumnType("bit");

                    b.Property<short>("CellPhone")
                        .HasColumnType("smallint");

                    b.Property<string>("ClientName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("CompanyCode")
                        .HasColumnType("smallint");

                    b.Property<short>("Computer")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("Designation")
                        .HasColumnType("smallint");

                    b.Property<bool>("DidNotAcceptCbx")
                        .HasColumnType("bit");

                    b.Property<short>("Discipline")
                        .HasColumnType("smallint");

                    b.Property<short>("E48Week")
                        .HasColumnType("smallint");

                    b.Property<short>("E52Week")
                        .HasColumnType("smallint");

                    b.Property<string>("EmployeeNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("EmployeeType")
                        .HasColumnType("smallint");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("GOTCbxMInternet")
                        .HasColumnType("bit");

                    b.Property<bool>("GOTCbxMNFStandards")
                        .HasColumnType("bit");

                    b.Property<bool>("GOTCbxTEExpenses")
                        .HasColumnType("bit");

                    b.Property<bool>("INCbxBCards")
                        .HasColumnType("bit");

                    b.Property<bool>("INCbxDPhone")
                        .HasColumnType("bit");

                    b.Property<bool>("INCbxDesktop")
                        .HasColumnType("bit");

                    b.Property<bool>("INCbxFieldLaptop")
                        .HasColumnType("bit");

                    b.Property<bool>("INCbxLaptop")
                        .HasColumnType("bit");

                    b.Property<bool>("INCbxMeetWithMarketing")
                        .HasColumnType("bit");

                    b.Property<bool>("INCbxOther")
                        .HasColumnType("bit");

                    b.Property<bool>("INCbxPResume")
                        .HasColumnType("bit");

                    b.Property<bool>("INCbxSPhone")
                        .HasColumnType("bit");

                    b.Property<bool>("INCbxUsbAccess")
                        .HasColumnType("bit");

                    b.Property<string>("INTxtOther")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobSiteLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("Location")
                        .HasColumnType("smallint");

                    b.Property<string>("ManagerEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManagerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("Mileage")
                        .HasColumnType("smallint");

                    b.Property<short>("MileageRate")
                        .HasColumnType("smallint");

                    b.Property<string>("MileageRateTxt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("Office")
                        .HasColumnType("smallint");

                    b.Property<string>("PWLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("PerDiem")
                        .HasColumnType("smallint");

                    b.Property<string>("PerDiemTxt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SECbxHHats")
                        .HasColumnType("bit");

                    b.Property<bool>("SECbxOther")
                        .HasColumnType("bit");

                    b.Property<bool>("SECbxSGlasses")
                        .HasColumnType("bit");

                    b.Property<bool>("SECbxSVests")
                        .HasColumnType("bit");

                    b.Property<short>("SEHatColor")
                        .HasColumnType("smallint");

                    b.Property<short>("SENeededType")
                        .HasColumnType("smallint");

                    b.Property<short>("SESize")
                        .HasColumnType("smallint");

                    b.Property<string>("SETxtOther")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("SF330Discipline")
                        .HasColumnType("smallint");

                    b.Property<string>("SHNeeded")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SSNeeded")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SeatingArrangement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("TypeCbxBManager")
                        .HasColumnType("bit");

                    b.Property<bool>("TypeCbxESAMTraining")
                        .HasColumnType("bit");

                    b.Property<bool>("TypeCbxETChange")
                        .HasColumnType("bit");

                    b.Property<bool>("TypeCbxMPosition")
                        .HasColumnType("bit");

                    b.Property<bool>("TypeCbxNewHire")
                        .HasColumnType("bit");

                    b.Property<bool>("TypeCbxReHire")
                        .HasColumnType("bit");

                    b.Property<bool>("TypeCbxTransfer")
                        .HasColumnType("bit");

                    b.Property<bool>("TypeCbxUnion")
                        .HasColumnType("bit");

                    b.Property<string>("TypeTechnical")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedByEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("cvCbxEZPass")
                        .HasColumnType("bit");

                    b.HasKey("Number");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Domain.Value", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Values");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Value 101"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Value 102"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Value 103"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
